### ISSUE TITLE
请问一下这个怎么安装？

### ISSUE THREAD

**Issue by ronghuaxueleng** [laixin86714802/spider-platform#1]
请问一下这个怎么安装？

**Comment by laixin86714802** [comment]
安装python3.4
cd ./spider-platform
pip install -r requirement.txt -i https://pypi.douban.com/simple
python server.py

**Comment by luxux** [comment]
但是在linux 下安装，怎么不能运行

**Comment by laixin86714802** [comment]
当时在windows平台下开发  有的模块应该不适用于linux

**Comment by oloeye** [comment]
非常感谢 @laixin86714802 ，想问下你现在还在维护本项目没有？

**Comment by GitMrs** [comment]
启动时报这个错了，请问一下怎么解决？ 
 File "server.py", line 50, in <module>
    debug=False
  File "server.py", line 23, in setup_event_loop
    IOLoop.instance().set_blocking_log_threshold(0.5)
  File "C:\Users\Mr\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\ioloop.py", line 461, in set_blocking_log_threshold
    self.set_blocking_signal_threshold(seconds, self.log_stack)
  File "C:\Users\Mr\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\ioloop.py", line 446, in set_blocking_signal_threshold
    raise NotImplementedError()
NotImplementedError

**Comment by laixin86714802** [comment]
我用的python3.4，tornado==4.5.3  应该是版本问题

**Comment by LenmonLin** [comment]
请问，动态解析网页太慢, 资源占用过高的问题有解决思路吗

**Comment by laixin86714802** [comment]
动态解析网页可以用selenium+chrome  不过和这个项目的设计不符  可以单独再写一个

**Comment by xulovemin** [comment]
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/work/modelclasify/spider-platform-master/server/spider/scrapy_thread.py", line 23, in crawl
    crawler_process.start()
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 309, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 1282, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 1262, in startRunning
    ReactorBase.startRunning(self)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 763, in startRunning
    raise error.ReactorAlreadyRunning()
twisted.internet.error.ReactorAlreadyRunning
Linux下运行报这个错误，能解决么

**Comment by dwcooper** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
penneryu, @jobsonlook, @0x70kg, @monkeym4ster, @zyqVizzzzz, @bentiancai629, @Ycomer, @peter0430snow, @ryantbd, @5l1v3r1, @crappycook, @zzxn, @xdewx, @stukid, @necusjz, @xrshao, @ml112265, @zhengyangas, @Trick93, @coder-layne
