### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by xulovemin** [laixin86714802/spider-platform#4]
Process Process-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/data/work/modelclasify/spider-platform-master/server/spider/scrapy_thread.py", line 23, in crawl
crawler_process.start()
File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 309, in start
reactor.run(installSignalHandlers=False) # blocking call
File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 1282, in run
self.startRunning(installSignalHandlers=installSignalHandlers)
File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 1262, in startRunning
ReactorBase.startRunning(self)
File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 763, in startRunning
raise error.ReactorAlreadyRunning()
twisted.internet.error.ReactorAlreadyRunning
Linux下运行报这个错误，能解决么

**Comment by laixin86714802** [comment]
你好，这个系统我只在windows下跑过，依赖包里的pywin32也是windows系统用。
这个项目是我初学python没多久写的，bug比较多，后续也没有维护，造成困扰，还请谅解。

**Comment by xulovemin** [comment]
额，没事没事，竟然回复了，我挺意外的

**Comment by xulovemin** [comment]
还有个问题，就是你解析css那块的爬虫运行代码，我发现有时候，yield的item就会是空的，但是还找不到原因，这个你有思路吗

**Comment by xulovemin** [comment]
因为是异步，所以也没跟出来，你这个是自己一点一点写出来的么，解析这块
